# Generated by Django 3.2.21 on 2023-09-28 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('plant_code', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ManagementVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_management_visits', models.IntegerField()),
                ('no_of_management_visits_file', models.FileField(null=True, upload_to='uploads/')),
                ('total_findings', models.IntegerField()),
                ('total_findings_file', models.FileField(null=True, upload_to='uploads/')),
                ('no_of_compilance_done', models.IntegerField()),
                ('no_of_compilance_done_file', models.FileField(null=True, upload_to='uploads/')),
                ('observation_pending', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
            options={
                'verbose_name': 'Management Visits',
                'verbose_name_plural': 'Management Visits',
            },
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_incidents', models.IntegerField()),
                ('no_of_occupation_illness', models.IntegerField()),
                ('no_of_environment_illness', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
            options={
                'verbose_name': 'Incidents',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='HSETrainingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hse_training_attendees', models.IntegerField()),
                ('duration_of_trainee', models.IntegerField()),
                ('hse_training_contractor', models.IntegerField()),
                ('duration_of_contractor', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
            options={
                'verbose_name': 'HSE Trainings',
                'verbose_name_plural': 'HSE Trainings',
            },
        ),
        migrations.CreateModel(
            name='HSEObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hse_observation', models.FileField(null=True, upload_to='uploads/')),
                ('daily_hse_observation', models.IntegerField()),
                ('stop_work_notice', models.IntegerField()),
                ('violation_memo_issued', models.IntegerField()),
                ('complaint_from_customer', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
            options={
                'verbose_name': 'HSE Observation',
                'verbose_name_plural': 'HSE Observation',
            },
        ),
        migrations.CreateModel(
            name='GeneralHse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_day_worked_file', models.FileField(null=True, upload_to='uploads/')),
                ('total_man_days_worked', models.IntegerField()),
                ('total_safe_man_hours', models.IntegerField()),
                ('no_of_person_inducted_site', models.IntegerField()),
                ('no_of_toolbox_attendees', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
            options={
                'verbose_name': 'General HSE',
                'verbose_name_plural': 'General HSE',
            },
        ),
    ]
