# Generated by Django 3.2.21 on 2023-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='no_of_attendees_amplus',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='no_of_attendees_contractor',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
