# Generated by Django 3.2.21 on 2023-10-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231003_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentmodel',
            old_name='status',
            new_name='form_status',
        ),
    ]
