# Generated by Django 3.2.21 on 2023-10-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_status_parentmodel_form_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
            options={
                'verbose_name': 'FinalSubmit',
                'verbose_name_plural': 'FinalSubmit',
            },
        ),
    ]
