# Generated by Django 3.2.21 on 2023-10-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hseobservationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationMemoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.IntegerField()),
                ('Date', models.TextField(max_length=100)),
                ('ProjectName', models.TextField(max_length=100)),
                ('ProjectCode', models.TextField(max_length=100)),
                ('BusinessSegment', models.TextField(max_length=100)),
                ('MemoNo', models.TextField(max_length=100)),
                ('Description', models.TextField(max_length=100)),
                ('ActionTaken', models.TextField(max_length=100)),
                ('IssuedBy', models.TextField(max_length=100)),
                ('IssuedTo', models.TextField(max_length=100)),
                ('PenaltyImposed', models.TextField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StopWorkForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.IntegerField()),
                ('Date', models.TextField(max_length=100)),
                ('Time', models.TextField(max_length=100)),
                ('Location', models.TextField(max_length=100)),
                ('PlantSite', models.TextField(max_length=100)),
                ('DescriptionOfIssue', models.TextField(max_length=100)),
                ('UnsafeAct', models.TextField(max_length=100)),
                ('Cateogry', models.TextField(max_length=100)),
                ('CorrrectiveActionTAken', models.TextField(max_length=100)),
                ('RemainingHazard', models.TextField(max_length=100)),
                ('ResponsiblePerson', models.TextField(max_length=100)),
                ('ClosureDate', models.TextField(max_length=100)),
                ('Status', models.TextField(max_length=100)),
                ('OpenEvidence', models.FileField(null=True, upload_to='formUploads')),
                ('ClosedEvidence', models.FileField(null=True, upload_to='formUploads')),
                ('Remark', models.TextField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
        ),
    ]
