# Generated by Django 3.2.21 on 2023-10-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_stopworkform_violationmemoform'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.IntegerField()),
                ('IncidentDate', models.TextField(max_length=100)),
                ('IncidentTime', models.TextField(max_length=100)),
                ('Location', models.TextField(max_length=100)),
                ('ExactLocation', models.TextField(max_length=100)),
                ('PlantSite', models.TextField(max_length=100)),
                ('ProjectCode', models.TextField(max_length=100)),
                ('DescriptionOfIncident', models.TextField(max_length=100)),
                ('RootCause', models.TextField(max_length=100)),
                ('TypeOfIncident', models.TextField(max_length=100)),
                ('HiPotentialIncident', models.TextField(max_length=100)),
                ('Cateogry', models.TextField(max_length=100)),
                ('ImmediateActionTaken', models.TextField(max_length=100)),
                ('CorrectiveAction', models.TextField(max_length=100)),
                ('PreventionAction', models.TextField(max_length=100)),
                ('ResponsiblePerson', models.TextField(max_length=100)),
                ('InvestigationStatus', models.TextField(max_length=100)),
                ('AttachReport', models.FileField(null=True, upload_to='formUploads')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.parentmodel')),
            ],
        ),
    ]
