# Generated by Django 3.2.21 on 2023-10-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_incidentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfObservers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SrNo', models.IntegerField()),
                ('nameOfPerson', models.TextField(max_length=50)),
                ('designation', models.TextField(max_length=50)),
                ('exactLocation', models.TextField(max_length=50)),
            ],
        ),
    ]
