# Generated by Django 3.2.21 on 2023-10-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_plant'),
    ]
