# Generated by Django 3.2.21 on 2023-10-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_parentmodel_plant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmodel',
            name='plant_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plant'),
        ),
    ]
