# Generated by Django 3.2.21 on 2023-10-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_parentmodel_plant_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParentModel',
            new_name='HSE',
        ),
    ]
