# Generated by Django 3.2.21 on 2023-10-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_parentmodel_hse'),
    ]

    operations = [
        migrations.AddField(
            model_name='hseobservationform',
            name='hse_observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hseobservation'),
        ),
        migrations.RemoveField(
            model_name='hseobservationform',
            name='parent',
        )
    ]
