# Generated by Django 3.2.21 on 2023-10-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20231017_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopworkform',
            name='parent',
        ),
        migrations.AddField(
            model_name='stopworkform',
            name='hse_observation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hseobservation'),
        ),
    ]
