# Generated by Django 3.2.21 on 2023-10-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20231017_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hse',
            options={'verbose_name': 'HSE', 'verbose_name_plural': 'HSE'},
        ),
        migrations.AlterModelOptions(
            name='hseobservationform',
            options={'verbose_name': 'Observation Form', 'verbose_name_plural': 'Observation Form'},
        ),
        migrations.AlterModelOptions(
            name='incidentform',
            options={'verbose_name': 'Incident Form', 'verbose_name_plural': 'Incident Form'},
        ),
        migrations.AlterModelOptions(
            name='stopworkform',
            options={'verbose_name': 'Stop Work Form', 'verbose_name_plural': 'Stop Work Form'},
        ),
        migrations.AlterModelOptions(
            name='violationmemoform',
            options={'verbose_name': 'Violation Memo Form', 'verbose_name_plural': 'Violation Memo Form'},
        ),
        migrations.RemoveField(
            model_name='incidentform',
            name='parent',
        ),
        migrations.AddField(
            model_name='incidentform',
            name='incident_insatnce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.incidents'),
        ),
    ]
