# Generated by Django 3.2.21 on 2023-10-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20231017_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentform',
            old_name='incident_insatnce',
            new_name='incident_instance',
        ),
    ]
