# Generated by Django 3.2.21 on 2023-10-18 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_incident_insatnce_incidentform_incident_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hseobservation',
            name='complaint_from_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='daily_hse_observation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='hse_observation',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hse'),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='stop_work_notice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='violation_memo_issued',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='no_of_environment_illness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='no_of_incidents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='no_of_occupation_illness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hse'),
        ),
    ]
