# Generated by Django 3.2.21 on 2023-10-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20231019_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalhse',
            name='committe_meetings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalhse',
            name='promotional_activities',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalhse',
            name='promotional_activities_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='generalhse',
            name='toolbox_talk_manhours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalhse',
            name='toolbox_talk_manhours_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='amplus_hse_trainings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='contractor_hse_trainings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
