# Generated by Django 3.2.21 on 2023-10-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20231020_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalhse',
            old_name='parent',
            new_name='hse',
        ),
    ]
