# Generated by Django 3.2.21 on 2023-10-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_parent_generalhse_hse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalhse',
            old_name='hse',
            new_name='parent',
        ),
    ]
