# Generated by Django 3.2.21 on 2023-10-23 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_hse_generalhse_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalhse',
            old_name='parent',
            new_name='hse',
        ),
        migrations.RenameField(
            model_name='hseobservation',
            old_name='parent',
            new_name='hse',
        ),
        migrations.RenameField(
            model_name='hsetrainingsmodel',
            old_name='parent',
            new_name='hse',
        ),
        migrations.RenameField(
            model_name='incidents',
            old_name='parent',
            new_name='hse',
        ),
        migrations.RenameField(
            model_name='managementvisits',
            old_name='parent',
            new_name='hse',
        ),
    ]
