# Generated by Django 3.2.21 on 2023-10-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20231023_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentform',
            old_name='incident_instance',
            new_name='incidents',
        ),
    ]
