# Generated by Django 3.2.21 on 2023-10-30 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_incident_instance_incidentform_incidents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hse',
            name='week_number',
        ),
        migrations.RemoveField(
            model_name='hse',
            name='year',
        ),
        migrations.AddField(
            model_name='hseobservationform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='incidentform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stopworkform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='violationmemoform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
