# Generated by Django 3.2.21 on 2023-10-31 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20231030_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalhse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hseobservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hsetrainingsmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='managementvisits',
            name='created_at',
        ),
        migrations.AddField(
            model_name='generalhse',
            name='submittedDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='hse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hseobservation',
            name='submittedDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='submittedDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='incidents',
            name='submittedDate',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='managementvisits',
            name='submittedDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
