# Generated by Django 3.2.21 on 2023-10-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20231031_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='hse',
            name='formSubmittedDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
