# Generated by Django 3.2.21 on 2023-11-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_hse_formsubmitteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalhse',
            name='formSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hseobservation',
            name='formSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='formSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidents',
            name='formSubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementvisits',
            name='formSubmitted',
            field=models.BooleanField(default=False),
        ),
    ]
