# Generated by Django 3.2.21 on 2023-11-24 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0030_auto_20231124_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalhse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_general_hse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalhse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_general_hse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_hse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_hse_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
