# Generated by Django 3.2.21 on 2023-11-25 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0031_auto_20231124_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='hseobservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hseobservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_hse_observation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hseobservation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hseobservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_hse_observation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_hse_training_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hsetrainingsmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_hse_training_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidents',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incidents',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_incidents_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidents',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incidents',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_incidents_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managementvisits',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='managementvisits',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_management_visits_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managementvisits',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='managementvisits',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_management_visits_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalhse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='generalhse',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
