# Generated by Django 3.2.21 on 2023-11-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20231125_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hseobservationform',
            options={'verbose_name': 'Observation Form', 'verbose_name_plural': 'Observation Forms'},
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='Cateogry',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='ClosureDate',
            new_name='closure_date',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='CorrrectiveActionTAken',
            new_name='corrective_action_taken',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='Observation',
            new_name='observation',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='PlantSite',
            new_name='plant_site',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='Remark',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='ResponsiblePerson',
            new_name='responsible_person',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='SrNo',
            new_name='sr_no',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='StopWork',
            new_name='stop_work',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='UnsafeCondition',
            new_name='unsafe_condition',
        ),
        migrations.RemoveField(
            model_name='hseobservationform',
            name='ClosedEvidence',
        ),
        migrations.RemoveField(
            model_name='hseobservationform',
            name='OpenEvidence',
        ),
        migrations.AddField(
            model_name='hseobservationform',
            name='closed_evidence',
            field=models.FileField(null=True, upload_to='form_uploads'),
        ),
        migrations.AddField(
            model_name='hseobservationform',
            name='open_evidence',
            field=models.FileField(null=True, upload_to='form_uploads'),
        ),
    ]
