# Generated by Django 3.2.21 on 2023-11-28 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_auto_20231128_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='hseobservationform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_observation_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hseobservationform',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hseobservationform',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_observation_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_incident_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentform',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incidentform',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_incident_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stopworkform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_stopwork_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stopworkform',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stopworkform',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_stopwork_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violationmemoform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_violationMemo_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violationmemoform',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='violationmemoform',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_violationMemo_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hseobservationform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
