# Generated by Django 3.2.21 on 2023-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20231128_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hseobservationform',
            name='datetime_observation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='closed_evidence',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='closure_date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='corrective_action_taken',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='description_of_issue',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='open_evidence',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='plant_site',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='remaining_hazard',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='remark',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='responsible_person',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='time',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='unsafe_act',
            field=models.CharField(max_length=300),
        ),
    ]
