# Generated by Django 3.2.21 on 2023-11-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20231128_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentform',
            old_name='hi_potential_incident',
            new_name='high_potential_incident',
        ),
    ]
