# Generated by Django 3.2.21 on 2023-11-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_hi_potential_incident_incidentform_high_potential_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hseobservationform',
            name='corrective_action_taken',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hseobservationform',
            name='observation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hseobservationform',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
