# Generated by Django 3.2.21 on 2023-11-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20231129_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='hseobservationform',
            name='form_closure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
