# Generated by Django 3.2.21 on 2023-11-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_hseobservationform_form_closure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hseobservationform',
            name='closure_date',
        ),
    ]
