# Generated by Django 3.2.21 on 2023-11-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_hseobservationform_closure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentform',
            name='datetime_observation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='corrective_action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='description_of_incident',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='immediate_action_taken',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='prevention_action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='root_cause',
            field=models.TextField(),
        ),
    ]
