# Generated by Django 3.2.21 on 2023-11-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20231129_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentform',
            name='incident_date',
        ),
        migrations.RemoveField(
            model_name='incidentform',
            name='incident_time',
        ),
        migrations.RemoveField(
            model_name='incidentform',
            name='sr_no',
        ),
    ]
