# Generated by Django 3.2.21 on 2023-11-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20231130_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopworkform',
            name='datetime_observation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stopworkform',
            name='form_closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hseobservationform',
            name='datetime_observation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='category',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], default='Incident_choices', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='high_potential_incident',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], default='high_potential_incident', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='type_of_incident',
            field=models.CharField(choices=[('Near Miss', 'Near Miss'), ('LTI', 'LTI'), ('MTI', 'MTI'), ('Fatal', 'Fatal'), ('Property Damage', 'Property Damage'), ('Flash Over', 'Flash Over'), ('Arc Flash', 'Arc Flash'), ('Fire', 'Fire')], default='Incident_type', max_length=20),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='corrective_action_taken',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stopworkform',
            name='description_of_issue',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='penalty_imposed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], default='Penalty_imposed', max_length=50),
        ),
    ]
