# Generated by Django 3.2.21 on 2023-11-30 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20231130_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopworkform',
            name='closure_date',
        ),
        migrations.RemoveField(
            model_name='stopworkform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stopworkform',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='stopworkform',
            name='time',
        ),
    ]
