# Generated by Django 3.2.21 on 2023-11-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20231130_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationmemoform',
            name='date_field',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='action_taken',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='business_segment',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='issued_by',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='issued_to',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='memo_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='project_code',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='violationmemoform',
            name='project_name',
            field=models.CharField(max_length=300),
        ),
    ]
