# Generated by Django 3.2.21 on 2023-11-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20231130_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationmemoform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='violationmemoform',
            name='sr_no',
        ),
    ]
