# Generated by Django 3.2.21 on 2023-11-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20231130_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalhse',
            name='toolbox_talk_manhours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='generalhse',
            name='total_safe_man_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='complaint_from_customer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='daily_hse_observation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='stop_work_notice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='violation_memo_issued',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hsetrainingsmodel',
            name='amplus_hse_trainings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hsetrainingsmodel',
            name='contractor_hse_trainings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hsetrainingsmodel',
            name='duration_of_contractor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hsetrainingsmodel',
            name='duration_of_trainee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hsetrainingsmodel',
            name='hse_training_attendees',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hsetrainingsmodel',
            name='hse_training_contractor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='category',
            field=models.CharField(choices=[('Recordable', 'Recordable'), ('Non-Recordable', 'Non-Recordable')], default='Incident_choices', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='no_of_environment_illness',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='no_of_incidents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='no_of_occupation_illness',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='managementvisits',
            name='no_of_compilance_done',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='managementvisits',
            name='no_of_management_visits',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='managementvisits',
            name='observation_pending',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='managementvisits',
            name='total_findings',
            field=models.PositiveIntegerField(),
        ),
    ]
