# Generated by Django 3.2.21 on 2023-12-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('app', '0049_auto_20231130_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSESegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=20)),
                ('homescape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.homescape')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.plant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.warehouse')),
            ],
        ),
        migrations.AlterField(
            model_name='hse',
            name='plant_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.plant'),
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
