# Generated by Django 3.2.21 on 2023-12-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231207_1453'),
        ('app', '0050_auto_20231207_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hsesegment',
            options={'verbose_name': 'HSESegment', 'verbose_name_plural': 'HSESegment'},
        ),
        migrations.AddField(
            model_name='hse',
            name='hse_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hsesegment'),
        ),
        migrations.AlterField(
            model_name='hse',
            name='plant_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.plant'),
        ),
    ]
