# Generated by Django 3.2.21 on 2023-12-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20231208_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hse',
            name='plant_code',
        ),
    ]
