# Generated by Django 3.2.21 on 2023-12-11 10:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0053_auto_20231211_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManagementVisits',
            new_name='ManagementVisit',
        ),
    ]
