# Generated by Django 3.2.21 on 2023-12-11 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0054_rename_managementvisits_managementvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSETraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hse_training_attendees', models.PositiveIntegerField()),
                ('attendees_amplus_file', models.FileField(null=True, upload_to='uploads/')),
                ('duration_of_trainee', models.FloatField()),
                ('hse_training_contractor', models.PositiveIntegerField()),
                ('attendees_contractor_file', models.FileField(null=True, upload_to='uploads/')),
                ('duration_of_contractor', models.FloatField()),
                ('amplus_hse_trainings', models.FloatField()),
                ('contractor_hse_trainings', models.FloatField()),
                ('submittedDate', models.DateField(default=None, null=True)),
                ('formSubmitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_hse_training_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HSE Trainings',
                'verbose_name_plural': 'HSE Trainings',
            },
        ),
        migrations.RenameField(
            model_name='incidents',
            old_name='no_of_incidents',
            new_name='no_of_incident',
        ),
        migrations.RenameField(
            model_name='managementvisit',
            old_name='no_of_management_visits',
            new_name='no_of_management_visit',
        ),
        migrations.RenameField(
            model_name='managementvisit',
            old_name='no_of_management_visits_file',
            new_name='no_of_management_visit_file',
        ),
        migrations.RenameField(
            model_name='managementvisit',
            old_name='total_findings',
            new_name='total_finding',
        ),
        migrations.RenameField(
            model_name='managementvisit',
            old_name='total_findings_file',
            new_name='total_finding_file',
        ),
        migrations.AlterField(
            model_name='generalhse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_general_hse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalhse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_general_hse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_hse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_hse_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_hse_observation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hseobservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_hse_observation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_incident_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managementvisit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_management_visit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managementvisit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_management_visit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HSETrainingsModel',
        ),
        migrations.AddField(
            model_name='hsetraining',
            name='hse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hse'),
        ),
        migrations.AddField(
            model_name='hsetraining',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_hse_training_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
