# Generated by Django 3.2.21 on 2023-12-11 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0055_auto_20231211_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hsetraining',
            options={'verbose_name': 'HSE Training', 'verbose_name_plural': 'HSE Training'},
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='closed_evidence',
            new_name='closed_evidence_file',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='datetime_observation',
            new_name='observation_datetime',
        ),
        migrations.RenameField(
            model_name='hseobservationform',
            old_name='open_evidence',
            new_name='open_evidence_file',
        ),
        migrations.AlterField(
            model_name='hseobservationform',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_observation_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hseobservationform',
            name='remark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hseobservationform',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_observation_form_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
