# Generated by Django 3.2.21 on 2023-12-12 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0057_auto_20231212_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopwork_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('plant_site', models.CharField(choices=[('Plant', 'Plant'), ('Site', 'Site')], default='Plant', max_length=10)),
                ('description_of_issue', models.TextField()),
                ('unsafe_condition', models.CharField(choices=[('Unsafe Act', 'UA'), ('Unsafe Condition', 'UC')], default='UC', max_length=50)),
                ('category', models.CharField(choices=[('Category', 'Category'), ('Legal Requirement', 'Legal Requirement'), ('Permit to Work', 'Permit to Work'), ('Electrical Work', 'Electrical Work'), ('Working at Height', 'Working at Height'), ('Lifting Operation', 'Lifting Operation'), ('Excavation', 'Excavation'), ('Hot Work', 'Hot Work'), ('Confined Space Work', 'Confined Space Work'), ('Manual Handling', 'Manual Handling'), ('Houskeeping', 'Houskeeping'), ('Chemical Handling', 'Chemical Handling'), ('SOP and Procedure Violation', 'SOP and Procedure Violation'), ('Medical Examination', 'Medical Examination'), ('PPE', 'PPE'), ('Vehicle Movment', 'Vehicle Movment'), ('Waste Management', 'Waste Management'), ('Welfare Facility', 'Welfare Facility'), ('General - Signage, Access, Walkway', 'General - Signage, Access, Walkway'), ('Emergency Preparedness', 'Emergency Preparedness')], default='Category', max_length=60)),
                ('corrective_action_taken', models.TextField()),
                ('remaining_hazard', models.CharField(max_length=50)),
                ('responsible_person', models.CharField(max_length=50)),
                ('form_closure_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], default='Status', max_length=50)),
                ('open_evidence', models.FileField(null=True, upload_to='form_uploads')),
                ('closed_evidence', models.FileField(null=True, upload_to='form_uploads')),
                ('remark', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_stopwork_form_records', to=settings.AUTH_USER_MODEL)),
                ('hse_observation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hseobservation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_b_stopwork_form_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stop Work Form',
                'verbose_name_plural': 'Stop Work Forms',
            },
        ),
        migrations.DeleteModel(
            name='StopWorkForm',
        ),
    ]
