# Generated by Django 3.2.21 on 2023-12-12 06:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0059_auto_20231212_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ViolationMemoForm',
            new_name='ViolationMemo',
        ),
    ]
