# Generated by Django 3.2.21 on 2023-12-12 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0060_rename_violationmemoform_violationmemo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentform',
            old_name='datetime_observation',
            new_name='incident_datetime',
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='exact_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='investigation_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='plant_site',
            field=models.CharField(choices=[('Plant', 'Plant'), ('Site', 'Site')], default='Plant', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='project_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentform',
            name='responsible_person',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='violationmemo',
            name='business_segment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='violationmemo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_violationMemo_form_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='violationmemo',
            name='issued_by',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='violationmemo',
            name='issued_to',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='violationmemo',
            name='project_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='violationmemo',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='violationmemo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_violationMemo_form_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
