# Generated by Django 3.2.21 on 2023-12-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0061_auto_20231212_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('exact_location', models.CharField(max_length=100)),
                ('plant_site', models.CharField(choices=[('Plant', 'Plant'), ('Site', 'Site')], default='Plant', max_length=10)),
                ('project_code', models.CharField(max_length=10)),
                ('description_of_incident', models.TextField()),
                ('root_cause', models.TextField()),
                ('type_of_incident', models.CharField(choices=[('Near Miss', 'Near Miss'), ('LTI', 'LTI'), ('MTI', 'MTI'), ('Fatal', 'Fatal'), ('Property Damage', 'Property Damage'), ('Flash Over', 'Flash Over'), ('Arc Flash', 'Arc Flash'), ('Fire', 'Fire')], default='Incident_type', max_length=20)),
                ('high_potential_incident', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], default='high_potential_incident', max_length=50)),
                ('category', models.CharField(choices=[('Recordable', 'Recordable'), ('Non-Recordable', 'Non-Recordable')], default='Incident_choices', max_length=50)),
                ('immediate_action_taken', models.TextField()),
                ('corrective_action', models.TextField()),
                ('prevention_action', models.TextField()),
                ('responsible_person', models.CharField(max_length=50)),
                ('investigation_status', models.CharField(max_length=50)),
                ('attach_report', models.FileField(null=True, upload_to='form_uploads')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_incident_form_records', to=settings.AUTH_USER_MODEL)),
                ('incidents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.incidents')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_incident_form_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Form',
                'verbose_name_plural': 'Incident Forms',
            },
        ),
        migrations.DeleteModel(
            name='IncidentForm',
        ),
    ]
