# Generated by Django 3.2.21 on 2023-12-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_rename_hseobservationform_subobservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hsesegment',
            options={'verbose_name': 'HSESegment', 'verbose_name_plural': 'HSESegments'},
        ),
        migrations.AlterModelOptions(
            name='subincident',
            options={'verbose_name': 'Incident Form', 'verbose_name_plural': 'Incident Form'},
        ),
        migrations.AlterModelOptions(
            name='subobservation',
            options={'verbose_name': 'Observation Form', 'verbose_name_plural': 'Observation Form'},
        ),
        migrations.AlterModelOptions(
            name='violationmemo',
            options={'verbose_name': 'Violation Memo Form', 'verbose_name_plural': 'Violation Memo Form'},
        ),
        migrations.RenameField(
            model_name='hse',
            old_name='formSubmittedDate',
            new_name='form_submitted_date',
        ),
        migrations.AlterField(
            model_name='stopwork',
            name='category',
            field=models.CharField(choices=[('Legal Requirement', 'Legal Requirement'), ('Permit to Work', 'Permit to Work'), ('Electrical Work', 'Electrical Work'), ('Working at Height', 'Working at Height'), ('Lifting Operation', 'Lifting Operation'), ('Excavation', 'Excavation'), ('Hot Work', 'Hot Work'), ('Confined Space Work', 'Confined Space Work'), ('Manual Handling', 'Manual Handling'), ('Houskeeping', 'Houskeeping'), ('Chemical Handling', 'Chemical Handling'), ('SOP and Procedure Violation', 'SOP and Procedure Violation'), ('Medical Examination', 'Medical Examination'), ('PPE', 'PPE'), ('Vehicle Movment', 'Vehicle Movment'), ('Waste Management', 'Waste Management'), ('Welfare Facility', 'Welfare Facility'), ('General - Signage, Access, Walkway', 'General - Signage, Access, Walkway'), ('Emergency Preparedness', 'Emergency Preparedness')], default='Category', max_length=60),
        ),
        migrations.AlterField(
            model_name='subobservation',
            name='category',
            field=models.CharField(choices=[('Legal Requirement', 'Legal Requirement'), ('Permit to Work', 'Permit to Work'), ('Electrical Work', 'Electrical Work'), ('Working at Height', 'Working at Height'), ('Lifting Operation', 'Lifting Operation'), ('Excavation', 'Excavation'), ('Hot Work', 'Hot Work'), ('Confined Space Work', 'Confined Space Work'), ('Manual Handling', 'Manual Handling'), ('Houskeeping', 'Houskeeping'), ('Chemical Handling', 'Chemical Handling'), ('SOP and Procedure Violation', 'SOP and Procedure Violation'), ('Medical Examination', 'Medical Examination'), ('PPE', 'PPE'), ('Vehicle Movment', 'Vehicle Movment'), ('Waste Management', 'Waste Management'), ('Welfare Facility', 'Welfare Facility'), ('General - Signage, Access, Walkway', 'General - Signage, Access, Walkway'), ('Emergency Preparedness', 'Emergency Preparedness')], default='Category', max_length=60),
        ),
    ]
