# Generated by Django 3.2.21 on 2023-12-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20231214_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalhse',
            old_name='formSubmitted',
            new_name='form_submitted',
        ),
        migrations.RenameField(
            model_name='hseobservation',
            old_name='formSubmitted',
            new_name='form_submitted',
        ),
        migrations.RenameField(
            model_name='hsetraining',
            old_name='formSubmitted',
            new_name='form_submitted',
        ),
        migrations.RenameField(
            model_name='incidents',
            old_name='formSubmitted',
            new_name='form_submitted',
        ),
        migrations.RenameField(
            model_name='managementvisit',
            old_name='formSubmitted',
            new_name='form_submitted',
        ),
    ]
