# Generated by Django 3.2.21 on 2023-12-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homescape',
            options={'verbose_name': 'HomeScape', 'verbose_name_plural': 'HomeScape'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'verbose_name': 'Plant', 'verbose_name_plural': 'Plant'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouse'},
        ),
    ]
